kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: huggingface-finetuning-image
  context: .
  dockerfile: ./Dockerfile

spec:
  operator: pytorch
  image: huggingface-finetuning-image
  command: "python3 finetuning.py --report_to none"


  # env:
  #   name: HUGGING_TOKEN
  #   value: ${HUGGING_TOKEN}

  tensorboard:
    enabled: true

  types:
    Master:
      count: 1
      resources:
        cpus: 8
        ramRatio: 4
        accelerators:
          gpu:
            count: 1
            type: gpu
            product: NVIDIA-A100-SXM4-80GB
    Worker:
      count: 1
      resources:
        cpus: 8
        ramRatio: 4
        accelerators:
          gpu:
            count: 1
            type: gpu
            product: NVIDIA-A100-SXM4-80GB