kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: huggingface-finetuning-image  # Nom de l'image Docker à construire
  context: . # Contexte local (répertoire courant) #https://github.com/foulhadj/embedding_finetuning.git #https://github.com/foulhadj/embedding_finetuning.git#main # Répertoire contenant le Dockerfile, `finetuning.py` et les données
  dockerfile: ./Dockerfile  # Chemin vers le Dockerfile

spec:
  operator: pytorch
  image: huggingface-finetuning-image  # Image Docker à utiliser pour l'exécution
  command: "python3 finetuning.py"  # Exécuter votre script Python

  tensorboard:
    enabled: true  # Activer TensorBoard pour surveiller les métriques d'entraînement

  types:
    Worker:
      count: 1
      resources:
        cpus: 16
        ramRatio: 4  # 16 * 4 = 64 Go de RAM
        accelerators:
          gpu:
            count: 2
            type: gpu
            product: Tesla-V100-SXM3-32GB
    # Worker:
    #   count: 0
    #   resources:
    #     cpus: 1
    #     ramRatio: 1