kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: huggingface-finetuning-image  # Nom de l'image Docker à construire
  context: . # Contexte local (répertoire courant) #https://github.com/foulhadj/embedding_finetuning.git #https://github.com/foulhadj/embedding_finetuning.git#main # Répertoire contenant le Dockerfile, `finetuning.py` et les données
  dockerfile: ./Dockerfile  # Chemin vers le Dockerfile

spec:
  operator: pytorch
  image: huggingface-finetuning-image  # Image Docker à utiliser pour l'exécution
  command: "python3 finetuning.py"  # Exécuter votre script Python

  tensorboard:
    enabled: true  # Activer TensorBoard pour surveiller les métriques d'entraînement

  types:
    Worker:
      count: 1
      resources:
        cpus: 2
        ramRatio: 16 # 32GB
        accelerators: # optional
          gpu:
            count: 2 # note that setting more than 1 MIG device per container is useless since only one will be usable https://docs.nvidia.com/datacenter/tesla/mig-user-guide/index.html#cuda-device-enumeration
            type: gpu
            product: NVIDIA-A100-SXM4-40GB
    # Worker:
    #   count: 0
    #   resources:
    #     cpus: 1
    #     ramRatio: 1