kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: huggingface-finetuning-image
  context: .
  dockerfile: ./Dockerfile

spec:
  operator: pytorch
  image: huggingface-finetuning-image
  command: "python3 finetuning.py; sleep 10"

  tensorboard:
    enabled: true

  types:
    Worker:
      count: 1
      resources:
        cpus: 8
        ramRatio: 4
        accelerators:
          gpu:
            count: 2
            type: gpu
            product: NVIDIA-A100-SXM4-80GB